apiVersion: v1
kind: ConfigMap
metadata:
  name: customc2-config
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  API_PREFIX: "/api/v1"
  STORAGE_DRIVER: "minio"
  MINIO_ENDPOINT: "customc2-minio:9000"
  MINIO_BUCKET: "c2-artifacts"
  LOCAL_STORAGE_DIR: "/app/data"
  AUTH_DISABLED: "false"
