apiVersion: v1
kind: Secret
metadata:
  name: customc2-secrets
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME_32_BYTES_HEX"
  DATABASE_URL: "postgresql://postgres:root@customc2-postgres:5432/customc2"
  MINIO_ACCESS_KEY: "minio"
  MINIO_SECRET_KEY: "minio123"
  DEFAULT_ADMIN_USER: "admin"
  DEFAULT_ADMIN_PASS: "ChangeMe_123!"
